UniversityManagementSystemWebApp/UniversityManagementSystemWebApp/Controllers/ViewAllocateRoomController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class ViewAllocateRoomController : Controller
    {
        //
        // GET: /ViewAllocateRoom/

        private SqlConnection connection =
           new SqlConnection(WebConfigurationManager.ConnectionStrings["UMSConnection"].ConnectionString);

        private List<AllocateClassRoom> allocateDetailes = new List<AllocateClassRoom>();
        public ActionResult AllocateWebGridView()
        {
            Department();
            return View(allocateDetailes);
        }

        [HttpPost]
        public ActionResult GetAllocateDetails()
        {
            Department();

            string query = "SELECT * FROM Course WHERE DepartmentId = '" + Request["selectedDepartment"] + "'";
            SqlCommand command = new SqlCommand(query, connection);
            connection.Open();
            SqlDataReader reader = command.ExecuteReader();

            // POPULATE THE LIST WITH BIRD DETAILS.
            while (reader.Read())
            {
                if (!DBNull.Value.Equals(reader["IsAllocated"]))
                {
                    allocateDetailes.Add(new AllocateClassRoom
                    {

                        CourseName = reader["Name"].ToString(),
                        CourseCode = reader["Code"].ToString(),
                        CourseId = int.Parse(reader["Id"].ToString()),

                        Details = reader["Id"].ToString()


                    });
                }
                else
                {

                    allocateDetailes.Add(new AllocateClassRoom
                    {
                        CourseName = reader["Name"].ToString(),
                        CourseCode= reader["Code"].ToString(),
                        CourseId = int.Parse(reader["Id"].ToString()),

                        Details = "Not Scheduled Yet"

                    });

                }
            }

            connection.Close();


            foreach (var details in allocateDetailes)
            {
                if (details.Details == "Not Scheduled Yet")
                {
                    details.Details = "Not Scheduled Yet";
                }
                else
                {
                    details.Details = GetRoomAndScheduled(details.CourseId);

                }
            }
            // RETURN DETAILS TO THE PARENT VIEW.
            return View("AllocateWebGridView", allocateDetailes);
        }

        private string scheduleDetails;
        private string GetRoomAndScheduled(int courseId)
        {
            string query = "SELECT t.CourseId, Code=(select Code from Course where Id=t.CourseId),Name=(select name from Course where Id=t.CourseId), Details = STUFF((SELECT ' R. No : ' + s.RoomNo +',  '+ s.Day +',  ' + s.FromTime+' -  '+s.EndTime+ ' ;' FROM AllocateClassRoom s WHERE s.CourseId = t.CourseId FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') FROM AllocateClassRoom t where t.CourseId='" + courseId + "' GROUP BY t.CourseId";
            SqlCommand command = new SqlCommand(query, connection);
            connection.Open();
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                scheduleDetails = reader["Details"].ToString();
            }

            connection.Close();
            reader.Close();
            return scheduleDetails;
        }
       

        void Department()
        {
            List<SelectListItem> departments = new List<SelectListItem>();

            string query = "SELECT * FROM Department";
            SqlCommand command = new SqlCommand(query, connection);
            connection.Open();
            SqlDataReader reader = command.ExecuteReader();

            departments.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "--Select Department--"
            });
            // POPULATE THE LIST WITH DATA.
            while (reader.Read())
            {
                departments.Add(new SelectListItem
                {

                    Text = reader["Name"].ToString(),
                    Value = reader["Id"].ToString(),
                    Selected = Request["selectedDepartment"] == reader["Id"].ToString() ? true : false
                });
            }

            // ADD LIST TO A ViewBag. WILL USE THIS LIST TO POPULATE THE DROPDOWNLIST IN OUR VIEW.
            ViewBag.selectedDepartment = departments;

            connection.Close();
        }

        //private string query =
        //    "SELECT t.CourseId,Code=(select Code from Course " +
        //    "where Id=t.CourseId),Name=(select name from Course where Id=t.CourseId)," +
        //    "Details = STUFF((SELECT ' R. No : ' + s.RoomNo +',  '+ s.Day +',  ' + s.FromTime+' -  '+s.EndTime+ ' ;' " +
        //    "FROM AllocateClassRoom s WHERE s.CourseId = t.CourseId FOR XML PATH(''), " +
        //    "TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') FROM AllocateClassRoom t GROUP BY t.CourseId";
    }
}

UniversityManagementSystemWebApp/UniversityManagementSystemWebApp/Views/ViewAllocateRoom/AllocateWebGridView.cshtml
@{
    ViewBag.Title = "Course Statistics";
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainView.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h4 style="font-size: 30pt; color: green; padding-left: 170px">University Management System</h4>

        @*<ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>*@
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        @*<div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>*@
        <div class="box-body">
            <head>
                <meta name="viewport" content="width=device-width" />
                <title>View Class Schedule And Room Allocation</title>
                <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
                <style>
                    select, p, div, input {
                        font: 17px Calibri;
                    }

                    .Full {
                        border: dotted 1px #555;
                        width: 500px;
                    }

                    .grid {
                        font: 17px Calibri;
                        width: 500px;
                        background-color: #FFF;
                        border: solid 1px #CD6736;
                    }

                        .grid td, th {
                            padding: 2px;
                            border: solid 1px #CD6736;
                            text-align: center;
                            text-transform: capitalize;
                        }

                    .grid-header {
                        background-color: #CD6736;
                        color: #FFF;
                        text-align: left;
                    }

                    .grid-footer {
                        color: #000;
                        font: 15px Calibri;
                        text-align: left;
                    }
                </style>
            </head>

            <body>

            <div style="padding-left: 50px">
                <br/>
                <h4 style="font-size: 25pt; color: green; padding-left: 0px">View Class Schedule And Room Allocation</h4><br/>


                <div style="border: 1px solid black; width: 550px;">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-6">

                                <br/><br/>

                                <br/>
                                @using (Html.BeginForm("GetAllocateDetails", "ViewAllocateRoom", FormMethod.Post, new {@Id = "WebGridForm"}))
                                {
                                    <div>
                                        Department : @Html.DropDownList("selectedDepartment", null, new {id = "selectDepartment"})
                                        <p>
                                    </div>
                                }
                                <br/><br/>

                                @if (Model.Count > 0)
                                {
                                    WebGrid objGrid = new WebGrid(source: Model, rowsPerPage: 5, canSort: false);
                                    @objGrid.GetHtml(
                                        tableStyle: "grid",
                                        headerStyle: "grid-header",
                                        footerStyle: "grid-footer",
                                        columns: objGrid.Columns(

                                            objGrid.Column("CourseCode", "Course Code"),
                                            objGrid.Column("CourseName", "Name"),
                                            objGrid.Column("Details", "Schedule Info")
                                            )
                                        )
                                }

                                @if (Model.Count == 0)
                                {
                                    WebGrid objGrid = new WebGrid(source: Model, rowsPerPage: 5, canSort: false);
                                    @objGrid.GetHtml(
                                        tableStyle: "grid",
                                        headerStyle: "grid-header",
                                        footerStyle: "grid-footer",
                                        columns: objGrid.Columns(
                                            objGrid.Column(" ", "Course Code"),
                                            objGrid.Column(" ", "Name"),
                                            objGrid.Column(" ", "Schedule Info")
                                            )
                                        )
                                }

                                <br/><br/><br/><br/>
                                @Html.ActionLink("Back to Home page", "Index", "Home", null, new {})
                                <br/><br/><br/><br/>
                            </div>
                        </div>
                    </div>
                </div>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                <script type="text/javascript">
                    $("body").on("change", "#selectDepartment", function() {
                        $('#WebGridForm')[0].submit();
                    });
                    $("body").on("click", ".Grid tfoot a", function() {
                        $('#WebGridForm').attr('action', $(this).attr('href')).submit();
                        return false;
                    });
                </script>
            </div>
            </body>
        </div>
    </section>
</div>